### ISSUE TITLE
add lincese in generated files

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-api-generator#2]
Generator should also add the EPL header.

**Comment by muka** [comment]
Hi, seems it is EPL already. Can you give some details on the issue?

**Comment by cskiraly** [comment]
The generator generated files, and these do not have an EPL header. It would be better to have an EPL header included in the generated content.

**Comment by muka** [comment]
Ok, thanks. The code takes from the `./template` folder eg. https://github.com/Agile-IoT/agile-api-generator/blob/master/template/swagger/root.tpl.yml

If I am not wrong the output should have already the correct license.

**Comment by cskiraly** [comment]
I see that some of the output files are without license header. E.g. docs/html/api.html
but also others. Can you update the generator? Thanks
